name: Lint, Test & Build
on:
  pull_request:
    branches:
      - "development"
jobs:
  Lint-Test-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Use Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting Rules
        run: npm run lint
      - name: Test the Code
        run: npm run test
      - name: Build
        run: npm run build
